---
mountOptions:
    default:     defaults,noatime
    btrfs:       defaults,noatime,compress=zstd:1
    btrfs_swap:  defaults
    btrfs_home:  defaults,noatime,compress=zstd:1

ssdExtraMountOptions:
    ext4:    discard
    xfs:     discard
    btrfs:   discard=async

crypttabOptions: luks,keyscript=/bin/cat
