---
services:
    - name: sddm
      mandatory: true
    - name: NetworkManager
      mandatory: true
    - name: systemd-timesyncd
      mandatory: false

targets:
    - name: graphical
      mandatory: true

disable:
    - name: apt-daily
    - name: apt-daily-upgrade
