---
defaultGroups:
    - users
    - lp
    - video
    - network
    - storage
    - wheel
    - audio
    - plugdev
    - netdev

autologinGroup:  autologin
sudoersGroup:    sudo
setRootPassword: false

# Username / hostname policy — align with Ubuntu to keep muscle memory.
userShell: /usr/bin/zsh
passwordRequirements:
    minLength: 8
    maxLength: -1
    libpwquality:
        - minlen=8
        - minclass=2
